services:
  comwork_cloud_api:
    restart: always
    image: ${CI_REGISTRY}/cwcloud-api:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api
      cache_from: &cwcloud_cache
        - type=registry,ref=${CI_REGISTRY}/cwcloud-api:${VERSION}

  comwork_cloud_consumer:
    restart: always
    image: ${CI_REGISTRY}/cwcloud-consumer:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: consumer
      cache_from: *cwcloud_cache

  comwork_cloud_scheduler:
    restart: always
    image: ${CI_REGISTRY}/cwcloud-scheduler:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: scheduler
      cache_from: *cwcloud_cache

  comwork_cloud_tests:
    image: ${CI_REGISTRY}/cwcloud-tests:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: unit_tests
      cache_from: *cwcloud_cache
    volumes:
      - ./cloud_environments_build.yml:/app/cloud_environments.yml

  comwork_cloud_linter:
    image: ${CI_REGISTRY}/cwcloud-linter:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: linter
      cache_from: *cwcloud_cache

  comwork_cloud_bandit:
    image: ${CI_REGISTRY}/cwcloud-bandit:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: code_scanner
      cache_from: *cwcloud_cache
    volumes:
      - .:/app
